-- Eight people who all follow each other, fifty photo posts, likes and
-- comments. Every account signs in with the password "snapgrove", and each
-- has a few unread notifications from the last day.

insert into users (email, passwordHash, handle, name, bio, avatarSeed, createdAt)
     values
            ('maya@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'maya', 'Maya Okafor', 'Chasing ridgelines and early light. Usually somewhere above the treeline.', 'avatar-1', now() - interval '60 days'),
            ('theo@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'theo', 'Theo Lindqvist', 'Architect by day. Bridges, towers and long shadows by night.', 'avatar-2', now() - interval '60 days'),
            ('priya@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'priya', 'Priya Raman', 'Coffee first. Then photos of coffee. Then more coffee.', 'avatar-3', now() - interval '60 days'),
            ('jonas@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'jonas', 'Jonas Weber', 'Salt air, grey water, and lighthouses I haven''t met yet.', 'avatar-4', now() - interval '60 days'),
            ('lena@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'lena', 'Lena Park', 'Shooting on old cameras. Collector of records and small objects.', 'avatar-5', now() - interval '60 days'),
            ('sam@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'sam', 'Sam Rivera', 'Macro and petals. The garden is bigger when you get closer.', 'avatar-6', now() - interval '60 days'),
            ('ada@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'ada', 'Ada Mensah', 'Forty countries and counting. Deserts are my favourite colour.', 'avatar-7', now() - interval '60 days'),
            ('kai@snapgrove.dev', crypt('snapgrove', genSalt('bf', 10)), 'kai', 'Kai Nakamura', 'Rails, roads, and where they go. Mostly the going.', 'avatar-8', now() - interval '60 days');

insert into follows (followerId, followeeId, createdAt)
     select a.id, b.id, now() - interval '30 days' + (random() * interval '10 days')
       from users a
       join users b on a.id <> b.id;

insert into posts (userId, seedPhoto, caption, createdAt)
     values
            ((select id from users where handle = 'jonas'), 'photo-244', 'This pelican has been on the same post all week.', now() - interval '1309 minutes'),
            ((select id from users where handle = 'sam'), 'photo-306', 'One white flower in the whole bed.', now() - interval '1978 minutes'),
            ((select id from users where handle = 'priya'), 'photo-63', 'Flat white in a red cup. The colour did the work.', now() - interval '2082 minutes'),
            ((select id from users where handle = 'lena'), 'photo-40', 'Portrait of a cat who did not consent to a portrait.', now() - interval '2278 minutes'),
            ((select id from users where handle = 'theo'), 'photo-259', 'Dusk over the expressway, the towers lighting up one by one.', now() - interval '2423 minutes'),
            ((select id from users where handle = 'kai'), 'photo-314', 'Open road. No destination today.', now() - interval '2568 minutes'),
            ((select id from users where handle = 'theo'), 'photo-299', 'Alleys are where the real architecture hides.', now() - interval '2707 minutes'),
            ((select id from users where handle = 'priya'), 'photo-312', 'Morning ritual, same cup for six years.', now() - interval '3091 minutes'),
            ((select id from users where handle = 'lena'), 'photo-39', 'Sunday soundtrack: side B, all the way through.', now() - interval '3217 minutes'),
            ((select id from users where handle = 'lena'), 'photo-45', 'Spotted this van downtown and had to stop.', now() - interval '3893 minutes'),
            ((select id from users where handle = 'ada'), 'photo-288', 'Old town rooftops from the clock tower.', now() - interval '5005 minutes'),
            ((select id from users where handle = 'ada'), 'photo-49', 'Santorini, finally. The white walls are blinding in the best way.', now() - interval '5430 minutes'),
            ((select id from users where handle = 'lena'), 'photo-237', 'Studio assistant on duty. Very serious about it.', now() - interval '5915 minutes'),
            ((select id from users where handle = 'theo'), 'photo-57', 'Empty street, 6am. The city before it wakes up.', now() - interval '6773 minutes'),
            ((select id from users where handle = 'maya'), 'photo-17', 'The trail through the pines this morning. Nobody else for miles.', now() - interval '8023 minutes'),
            ((select id from users where handle = 'kai'), 'photo-88', 'Highway rush from the overpass.', now() - interval '8165 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-10', 'Grey sea, grey sky, perfect day.', now() - interval '9460 minutes'),
            ((select id from users where handle = 'theo'), 'photo-84', 'Suspension cables at night. Engineering is poetry.', now() - interval '9847 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-58', 'Lighthouse number 23 on the list.', now() - interval '9863 minutes'),
            ((select id from users where handle = 'ada'), 'photo-211', 'Tall ships in the old harbour, every house a different colour.', now() - interval '10305 minutes'),
            ((select id from users where handle = 'kai'), 'photo-242', 'Rails at sunset, the best time for trains.', now() - interval '10318 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-74', 'Blue on blue out past the harbour.', now() - interval '11170 minutes'),
            ((select id from users where handle = 'kai'), 'photo-316', 'Boardwalk into the marsh. The quiet kind of route.', now() - interval '11233 minutes'),
            ((select id from users where handle = 'theo'), 'photo-43', 'Brooklyn Bridge in black and white. Some things only work in mono.', now() - interval '11280 minutes'),
            ((select id from users where handle = 'ada'), 'photo-219', 'Safari day three. She walked right past the truck.', now() - interval '11499 minutes'),
            ((select id from users where handle = 'priya'), 'photo-75', 'Grapes from the vineyard tour. Tasted even better than they look.', now() - interval '11873 minutes'),
            ((select id from users where handle = 'sam'), 'photo-55', 'New leaves on the balcony plant. She lives!', now() - interval '12227 minutes'),
            ((select id from users where handle = 'maya'), 'photo-28', 'Found the valley everyone talks about. It''s greener in person.', now() - interval '13726 minutes'),
            ((select id from users where handle = 'ada'), 'photo-247', 'Dunes at golden hour. The sand changes colour every minute.', now() - interval '13843 minutes'),
            ((select id from users where handle = 'priya'), 'photo-292', 'Market haul. Everything is back in season.', now() - interval '14036 minutes'),
            ((select id from users where handle = 'sam'), 'photo-239', 'Make a wish.', now() - interval '14732 minutes'),
            ((select id from users where handle = 'priya'), 'photo-225', 'Afternoon tea, slow steep, no plans.', now() - interval '14874 minutes'),
            ((select id from users where handle = 'kai'), 'photo-233', 'Tracks curving into the hills. The station is a mile that way.', now() - interval '14973 minutes'),
            ((select id from users where handle = 'lena'), 'photo-91', 'New-old camera day. 1978 and still perfect.', now() - interval '15281 minutes'),
            ((select id from users where handle = 'lena'), 'photo-250', 'The rangefinder that started it all.', now() - interval '16047 minutes'),
            ((select id from users where handle = 'maya'), 'photo-18', 'Grass taller than my knees at the trailhead.', now() - interval '16248 minutes'),
            ((select id from users where handle = 'maya'), 'photo-29', 'Snow on the ridge in September. Winter is early up here.', now() - interval '16291 minutes'),
            ((select id from users where handle = 'priya'), 'photo-30', 'Monday mug. Please don''t talk to me for ten minutes.', now() - interval '16300 minutes'),
            ((select id from users where handle = 'sam'), 'photo-35', 'Pollen up close. Bees know what they''re doing.', now() - interval '16800 minutes'),
            ((select id from users where handle = 'kai'), 'photo-69', 'Old branch line, trains stopped running years ago.', now() - interval '17234 minutes'),
            ((select id from users where handle = 'sam'), 'photo-309', 'Backlit leaf, all the little veins showing.', now() - interval '17448 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-77', 'End of the pier. The best seat in town.', now() - interval '17973 minutes'),
            ((select id from users where handle = 'maya'), 'photo-256', 'Fresh powder on the north slope.', now() - interval '18312 minutes'),
            ((select id from users where handle = 'sam'), 'photo-82', 'Cherry blossom season is short, so I went every day.', now() - interval '18518 minutes'),
            ((select id from users where handle = 'maya'), 'photo-287', 'Rolling hills on the way down. Could walk this forever.', now() - interval '18801 minutes'),
            ((select id from users where handle = 'maya'), 'photo-235', 'Summit day. Legs are done, heart is full.', now() - interval '18847 minutes'),
            ((select id from users where handle = 'ada'), 'photo-261', 'Stood in the shadow of this and felt very small.', now() - interval '19027 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-295', 'Storm swell rolling in. Stayed well back for this one.', now() - interval '19212 minutes'),
            ((select id from users where handle = 'theo'), 'photo-238', 'Skyline from the observation deck. Every window a story.', now() - interval '19501 minutes'),
            ((select id from users where handle = 'jonas'), 'photo-14', 'Rocks at low tide. The coast keeps rearranging itself.', now() - interval '19979 minutes');

insert into likes (postId, userId, createdAt)
     values
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'lena'), now() - interval '125 minutes'),
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'ada'), now() - interval '635 minutes'),
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'maya'), now() - interval '1184 minutes'),
            ((select id from posts where seedPhoto = 'photo-306'), (select id from users where handle = 'jonas'), now() - interval '121 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'theo'), now() - interval '1840 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'lena'), now() - interval '1646 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'ada'), now() - interval '1139 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'sam'), now() - interval '561 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'maya'), now() - interval '1764 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'jonas'), now() - interval '1141 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'theo'), now() - interval '17 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'maya'), now() - interval '597 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'jonas'), now() - interval '1717 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'kai'), now() - interval '2190 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'sam'), now() - interval '1513 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'priya'), now() - interval '1306 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'ada'), now() - interval '1631 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'kai'), now() - interval '1635 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'maya'), now() - interval '1615 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'lena'), now() - interval '425 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'jonas'), now() - interval '1973 minutes'),
            ((select id from posts where seedPhoto = 'photo-259'), (select id from users where handle = 'priya'), now() - interval '1641 minutes'),
            ((select id from posts where seedPhoto = 'photo-314'), (select id from users where handle = 'maya'), now() - interval '1805 minutes'),
            ((select id from posts where seedPhoto = 'photo-314'), (select id from users where handle = 'theo'), now() - interval '665 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'sam'), now() - interval '1 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'maya'), now() - interval '2322 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'ada'), now() - interval '620 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'jonas'), now() - interval '1909 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'lena'), now() - interval '1968 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'maya'), now() - interval '1982 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'sam'), now() - interval '1278 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'theo'), now() - interval '352 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'priya'), now() - interval '601 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'jonas'), now() - interval '2827 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'theo'), now() - interval '2225 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'maya'), now() - interval '111 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'ada'), now() - interval '3106 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'sam'), now() - interval '2164 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'priya'), now() - interval '2182 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'theo'), now() - interval '2219 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'priya'), now() - interval '2289 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'sam'), now() - interval '3869 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'maya'), now() - interval '2124 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'lena'), now() - interval '1587 minutes'),
            ((select id from posts where seedPhoto = 'photo-49'), (select id from users where handle = 'lena'), now() - interval '5350 minutes'),
            ((select id from posts where seedPhoto = 'photo-49'), (select id from users where handle = 'kai'), now() - interval '2819 minutes'),
            ((select id from posts where seedPhoto = 'photo-49'), (select id from users where handle = 'maya'), now() - interval '5269 minutes'),
            ((select id from posts where seedPhoto = 'photo-49'), (select id from users where handle = 'jonas'), now() - interval '695 minutes'),
            ((select id from posts where seedPhoto = 'photo-237'), (select id from users where handle = 'kai'), now() - interval '1463 minutes'),
            ((select id from posts where seedPhoto = 'photo-237'), (select id from users where handle = 'ada'), now() - interval '3555 minutes'),
            ((select id from posts where seedPhoto = 'photo-237'), (select id from users where handle = 'theo'), now() - interval '5209 minutes'),
            ((select id from posts where seedPhoto = 'photo-237'), (select id from users where handle = 'jonas'), now() - interval '2724 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'ada'), now() - interval '1393 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'lena'), now() - interval '1041 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'kai'), now() - interval '226 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'sam'), now() - interval '1239 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'jonas'), now() - interval '4840 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'maya'), now() - interval '3813 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'priya'), now() - interval '6607 minutes'),
            ((select id from posts where seedPhoto = 'photo-17'), (select id from users where handle = 'ada'), now() - interval '176 minutes'),
            ((select id from posts where seedPhoto = 'photo-17'), (select id from users where handle = 'jonas'), now() - interval '117 minutes'),
            ((select id from posts where seedPhoto = 'photo-17'), (select id from users where handle = 'priya'), now() - interval '6549 minutes'),
            ((select id from posts where seedPhoto = 'photo-17'), (select id from users where handle = 'sam'), now() - interval '7954 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'sam'), now() - interval '230 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'theo'), now() - interval '2064 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'jonas'), now() - interval '1744 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'ada'), now() - interval '2400 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'maya'), now() - interval '4106 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'sam'), now() - interval '998 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'lena'), now() - interval '5797 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'theo'), now() - interval '7507 minutes'),
            ((select id from posts where seedPhoto = 'photo-84'), (select id from users where handle = 'kai'), now() - interval '2455 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'maya'), now() - interval '1739 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'sam'), now() - interval '9180 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'kai'), now() - interval '931 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'priya'), now() - interval '4072 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'lena'), now() - interval '3135 minutes'),
            ((select id from posts where seedPhoto = 'photo-58'), (select id from users where handle = 'theo'), now() - interval '4538 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'maya'), now() - interval '10036 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'lena'), now() - interval '8283 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'jonas'), now() - interval '9931 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'kai'), now() - interval '8392 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'sam'), now() - interval '3268 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'theo'), now() - interval '4542 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'priya'), now() - interval '7412 minutes'),
            ((select id from posts where seedPhoto = 'photo-242'), (select id from users where handle = 'jonas'), now() - interval '7018 minutes'),
            ((select id from posts where seedPhoto = 'photo-242'), (select id from users where handle = 'priya'), now() - interval '1199 minutes'),
            ((select id from posts where seedPhoto = 'photo-242'), (select id from users where handle = 'maya'), now() - interval '3485 minutes'),
            ((select id from posts where seedPhoto = 'photo-242'), (select id from users where handle = 'theo'), now() - interval '4961 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'theo'), now() - interval '3598 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'ada'), now() - interval '1543 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'priya'), now() - interval '6526 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'kai'), now() - interval '7984 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'lena'), now() - interval '2668 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'maya'), now() - interval '10942 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'sam'), now() - interval '3666 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'priya'), now() - interval '5219 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'jonas'), now() - interval '1511 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'theo'), now() - interval '5996 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'ada'), now() - interval '320 minutes'),
            ((select id from posts where seedPhoto = 'photo-43'), (select id from users where handle = 'sam'), now() - interval '8393 minutes'),
            ((select id from posts where seedPhoto = 'photo-43'), (select id from users where handle = 'kai'), now() - interval '1054 minutes'),
            ((select id from posts where seedPhoto = 'photo-43'), (select id from users where handle = 'jonas'), now() - interval '1849 minutes'),
            ((select id from posts where seedPhoto = 'photo-219'), (select id from users where handle = 'maya'), now() - interval '2123 minutes'),
            ((select id from posts where seedPhoto = 'photo-219'), (select id from users where handle = 'theo'), now() - interval '6919 minutes'),
            ((select id from posts where seedPhoto = 'photo-219'), (select id from users where handle = 'priya'), now() - interval '11076 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'jonas'), now() - interval '6969 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'maya'), now() - interval '1187 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'kai'), now() - interval '4407 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'ada'), now() - interval '276 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'sam'), now() - interval '10395 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'lena'), now() - interval '1452 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'maya'), now() - interval '4389 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'priya'), now() - interval '10186 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'lena'), now() - interval '2118 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'jonas'), now() - interval '708 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'priya'), now() - interval '4104 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'jonas'), now() - interval '606 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'lena'), now() - interval '252 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'kai'), now() - interval '303 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'sam'), now() - interval '12011 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'ada'), now() - interval '8285 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'theo'), now() - interval '9029 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'maya'), now() - interval '8945 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'sam'), now() - interval '13675 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'jonas'), now() - interval '6441 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'lena'), now() - interval '8302 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'ada'), now() - interval '234 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'theo'), now() - interval '1159 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'lena'), now() - interval '10248 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'jonas'), now() - interval '12139 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'maya'), now() - interval '4188 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'sam'), now() - interval '7058 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'jonas'), now() - interval '7528 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'lena'), now() - interval '3037 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'priya'), now() - interval '2582 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'theo'), now() - interval '4408 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'ada'), now() - interval '7305 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'kai'), now() - interval '60 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'maya'), now() - interval '4313 minutes'),
            ((select id from posts where seedPhoto = 'photo-225'), (select id from users where handle = 'jonas'), now() - interval '18 minutes'),
            ((select id from posts where seedPhoto = 'photo-225'), (select id from users where handle = 'theo'), now() - interval '5495 minutes'),
            ((select id from posts where seedPhoto = 'photo-233'), (select id from users where handle = 'maya'), now() - interval '4329 minutes'),
            ((select id from posts where seedPhoto = 'photo-91'), (select id from users where handle = 'jonas'), now() - interval '683 minutes'),
            ((select id from posts where seedPhoto = 'photo-91'), (select id from users where handle = 'sam'), now() - interval '6455 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'priya'), now() - interval '1385 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'ada'), now() - interval '9595 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'theo'), now() - interval '15690 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'priya'), now() - interval '14908 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'theo'), now() - interval '8582 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'sam'), now() - interval '12335 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'lena'), now() - interval '8264 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'jonas'), now() - interval '9314 minutes'),
            ((select id from posts where seedPhoto = 'photo-18'), (select id from users where handle = 'ada'), now() - interval '13680 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'ada'), now() - interval '10439 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'sam'), now() - interval '5910 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'priya'), now() - interval '15721 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'theo'), now() - interval '1719 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'lena'), now() - interval '6171 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'jonas'), now() - interval '13695 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'kai'), now() - interval '7396 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'maya'), now() - interval '12072 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'ada'), now() - interval '7764 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'sam'), now() - interval '4132 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'kai'), now() - interval '13259 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'jonas'), now() - interval '1220 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'jonas'), now() - interval '1532 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'kai'), now() - interval '6498 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'ada'), now() - interval '2539 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'maya'), now() - interval '4831 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'theo'), now() - interval '10872 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'priya'), now() - interval '8322 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'priya'), now() - interval '16044 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'sam'), now() - interval '9531 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'maya'), now() - interval '16926 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'theo'), now() - interval '9357 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'maya'), now() - interval '12677 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'lena'), now() - interval '6876 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'jonas'), now() - interval '6905 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'priya'), now() - interval '2445 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'lena'), now() - interval '118 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'kai'), now() - interval '16112 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'maya'), now() - interval '14771 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'theo'), now() - interval '13285 minutes'),
            ((select id from posts where seedPhoto = 'photo-256'), (select id from users where handle = 'kai'), now() - interval '10857 minutes'),
            ((select id from posts where seedPhoto = 'photo-82'), (select id from users where handle = 'kai'), now() - interval '3934 minutes'),
            ((select id from posts where seedPhoto = 'photo-82'), (select id from users where handle = 'priya'), now() - interval '6415 minutes'),
            ((select id from posts where seedPhoto = 'photo-82'), (select id from users where handle = 'jonas'), now() - interval '385 minutes'),
            ((select id from posts where seedPhoto = 'photo-287'), (select id from users where handle = 'jonas'), now() - interval '14027 minutes'),
            ((select id from posts where seedPhoto = 'photo-235'), (select id from users where handle = 'ada'), now() - interval '8708 minutes'),
            ((select id from posts where seedPhoto = 'photo-235'), (select id from users where handle = 'priya'), now() - interval '14295 minutes'),
            ((select id from posts where seedPhoto = 'photo-235'), (select id from users where handle = 'kai'), now() - interval '16744 minutes'),
            ((select id from posts where seedPhoto = 'photo-261'), (select id from users where handle = 'theo'), now() - interval '13464 minutes'),
            ((select id from posts where seedPhoto = 'photo-261'), (select id from users where handle = 'sam'), now() - interval '14774 minutes'),
            ((select id from posts where seedPhoto = 'photo-261'), (select id from users where handle = 'maya'), now() - interval '4541 minutes'),
            ((select id from posts where seedPhoto = 'photo-261'), (select id from users where handle = 'lena'), now() - interval '9379 minutes'),
            ((select id from posts where seedPhoto = 'photo-261'), (select id from users where handle = 'priya'), now() - interval '15912 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'theo'), now() - interval '9233 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'kai'), now() - interval '9758 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'lena'), now() - interval '8381 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'sam'), now() - interval '8526 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'ada'), now() - interval '13311 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'lena'), now() - interval '16404 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'maya'), now() - interval '16289 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'priya'), now() - interval '18036 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'sam'), now() - interval '7210 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'ada'), now() - interval '14844 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'jonas'), now() - interval '10907 minutes'),
            ((select id from posts where seedPhoto = 'photo-14'), (select id from users where handle = 'priya'), now() - interval '7836 minutes');

insert into comments (postId, userId, body, createdAt)
     values
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'priya'), 'This is stunning.', now() - interval '711 minutes'),
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'ada'), 'So peaceful.', now() - interval '946 minutes'),
            ((select id from posts where seedPhoto = 'photo-244'), (select id from users where handle = 'lena'), 'Absolutely gorgeous.', now() - interval '345 minutes'),
            ((select id from posts where seedPhoto = 'photo-306'), (select id from users where handle = 'kai'), 'The colours are unreal.', now() - interval '589 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'jonas'), 'The colours are unreal.', now() - interval '946 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'ada'), 'Framed perfectly.', now() - interval '340 minutes'),
            ((select id from posts where seedPhoto = 'photo-63'), (select id from users where handle = 'lena'), 'Wow. Just wow.', now() - interval '620 minutes'),
            ((select id from posts where seedPhoto = 'photo-40'), (select id from users where handle = 'ada'), 'Absolutely gorgeous.', now() - interval '2112 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'maya'), 'I can almost hear it.', now() - interval '289 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'jonas'), 'Need a print of this.', now() - interval '2516 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'sam'), 'Saving this one.', now() - interval '609 minutes'),
            ((select id from posts where seedPhoto = 'photo-299'), (select id from users where handle = 'kai'), 'So peaceful.', now() - interval '1034 minutes'),
            ((select id from posts where seedPhoto = 'photo-312'), (select id from users where handle = 'maya'), 'Every post of yours is better than the last.', now() - interval '3071 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'ada'), 'Take me with you next time.', now() - interval '2852 minutes'),
            ((select id from posts where seedPhoto = 'photo-39'), (select id from users where handle = 'maya'), 'So peaceful.', now() - interval '2124 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'priya'), 'Wow. Just wow.', now() - interval '3302 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'ada'), 'Need a print of this.', now() - interval '3352 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'theo'), 'Wow. Just wow.', now() - interval '3031 minutes'),
            ((select id from posts where seedPhoto = 'photo-45'), (select id from users where handle = 'sam'), 'How early did you have to get up for this?', now() - interval '819 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'priya'), 'Wow. Just wow.', now() - interval '660 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'jonas'), 'Wow. Just wow.', now() - interval '837 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'kai'), 'I can almost hear it.', now() - interval '3851 minutes'),
            ((select id from posts where seedPhoto = 'photo-288'), (select id from users where handle = 'lena'), 'I can almost hear it.', now() - interval '2767 minutes'),
            ((select id from posts where seedPhoto = 'photo-57'), (select id from users where handle = 'sam'), 'Absolutely gorgeous.', now() - interval '6771 minutes'),
            ((select id from posts where seedPhoto = 'photo-88'), (select id from users where handle = 'ada'), 'Every post of yours is better than the last.', now() - interval '4805 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'kai'), 'The colours are unreal.', now() - interval '8714 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'sam'), 'How early did you have to get up for this?', now() - interval '8578 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'lena'), 'Goals.', now() - interval '307 minutes'),
            ((select id from posts where seedPhoto = 'photo-10'), (select id from users where handle = 'theo'), 'Absolutely gorgeous.', now() - interval '3001 minutes'),
            ((select id from posts where seedPhoto = 'photo-84'), (select id from users where handle = 'priya'), 'Absolutely gorgeous.', now() - interval '7758 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'lena'), 'Take me with you next time.', now() - interval '8573 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'jonas'), 'I can almost hear it.', now() - interval '9168 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'kai'), 'The colours are unreal.', now() - interval '7333 minutes'),
            ((select id from posts where seedPhoto = 'photo-211'), (select id from users where handle = 'theo'), 'Where is this? Adding it to my list.', now() - interval '6827 minutes'),
            ((select id from posts where seedPhoto = 'photo-74'), (select id from users where handle = 'ada'), 'How early did you have to get up for this?', now() - interval '7071 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'lena'), 'Beautiful shot!', now() - interval '7217 minutes'),
            ((select id from posts where seedPhoto = 'photo-316'), (select id from users where handle = 'jonas'), 'Need a print of this.', now() - interval '297 minutes'),
            ((select id from posts where seedPhoto = 'photo-43'), (select id from users where handle = 'maya'), 'Take me with you next time.', now() - interval '1378 minutes'),
            ((select id from posts where seedPhoto = 'photo-219'), (select id from users where handle = 'jonas'), 'How early did you have to get up for this?', now() - interval '8792 minutes'),
            ((select id from posts where seedPhoto = 'photo-219'), (select id from users where handle = 'theo'), 'This made my morning.', now() - interval '9349 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'maya'), 'Okay this one is my new wallpaper.', now() - interval '3644 minutes'),
            ((select id from posts where seedPhoto = 'photo-75'), (select id from users where handle = 'sam'), 'Where is this? Adding it to my list.', now() - interval '4333 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'ada'), 'The light here!', now() - interval '4291 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'theo'), 'I can almost hear it.', now() - interval '2968 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'maya'), 'Saving this one.', now() - interval '5112 minutes'),
            ((select id from posts where seedPhoto = 'photo-55'), (select id from users where handle = 'kai'), 'How early did you have to get up for this?', now() - interval '4998 minutes'),
            ((select id from posts where seedPhoto = 'photo-28'), (select id from users where handle = 'sam'), 'Wow. Just wow.', now() - interval '7779 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'sam'), 'Every post of yours is better than the last.', now() - interval '3762 minutes'),
            ((select id from posts where seedPhoto = 'photo-247'), (select id from users where handle = 'theo'), 'Beautiful shot!', now() - interval '3255 minutes'),
            ((select id from posts where seedPhoto = 'photo-292'), (select id from users where handle = 'maya'), 'The mood in this is perfect.', now() - interval '1385 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'priya'), 'Wow. Just wow.', now() - interval '5301 minutes'),
            ((select id from posts where seedPhoto = 'photo-239'), (select id from users where handle = 'lena'), 'That composition though.', now() - interval '565 minutes'),
            ((select id from posts where seedPhoto = 'photo-225'), (select id from users where handle = 'maya'), 'Saving this one.', now() - interval '8238 minutes'),
            ((select id from posts where seedPhoto = 'photo-225'), (select id from users where handle = 'lena'), 'Wow. Just wow.', now() - interval '3293 minutes'),
            ((select id from posts where seedPhoto = 'photo-225'), (select id from users where handle = 'jonas'), 'Love the tones.', now() - interval '8270 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'kai'), 'Every post of yours is better than the last.', now() - interval '12523 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'theo'), 'This made my morning.', now() - interval '11808 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'sam'), 'That composition though.', now() - interval '2449 minutes'),
            ((select id from posts where seedPhoto = 'photo-250'), (select id from users where handle = 'jonas'), 'Absolutely gorgeous.', now() - interval '11865 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'theo'), 'Take me with you next time.', now() - interval '8017 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'ada'), 'Goals.', now() - interval '55 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'kai'), 'Okay this one is my new wallpaper.', now() - interval '13070 minutes'),
            ((select id from posts where seedPhoto = 'photo-29'), (select id from users where handle = 'priya'), 'How early did you have to get up for this?', now() - interval '12260 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'theo'), 'I can almost hear it.', now() - interval '12394 minutes'),
            ((select id from posts where seedPhoto = 'photo-30'), (select id from users where handle = 'ada'), 'I was just there last year, brings back memories.', now() - interval '3781 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'lena'), 'This is stunning.', now() - interval '4373 minutes'),
            ((select id from posts where seedPhoto = 'photo-35'), (select id from users where handle = 'kai'), 'The light here!', now() - interval '15808 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'jonas'), 'That composition though.', now() - interval '6530 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'ada'), 'This made my morning.', now() - interval '2814 minutes'),
            ((select id from posts where seedPhoto = 'photo-69'), (select id from users where handle = 'maya'), 'That composition though.', now() - interval '574 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'maya'), 'The colours are unreal.', now() - interval '11782 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'theo'), 'Take me with you next time.', now() - interval '16671 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'lena'), 'Beautiful shot!', now() - interval '3693 minutes'),
            ((select id from posts where seedPhoto = 'photo-309'), (select id from users where handle = 'priya'), 'Wow. Just wow.', now() - interval '11967 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'ada'), 'So peaceful.', now() - interval '13638 minutes'),
            ((select id from posts where seedPhoto = 'photo-77'), (select id from users where handle = 'theo'), 'Every post of yours is better than the last.', now() - interval '12325 minutes'),
            ((select id from posts where seedPhoto = 'photo-82'), (select id from users where handle = 'priya'), 'Need a print of this.', now() - interval '2130 minutes'),
            ((select id from posts where seedPhoto = 'photo-82'), (select id from users where handle = 'kai'), 'Obsessed with this.', now() - interval '12785 minutes'),
            ((select id from posts where seedPhoto = 'photo-287'), (select id from users where handle = 'kai'), 'Where is this? Adding it to my list.', now() - interval '9196 minutes'),
            ((select id from posts where seedPhoto = 'photo-287'), (select id from users where handle = 'theo'), 'The mood in this is perfect.', now() - interval '1692 minutes'),
            ((select id from posts where seedPhoto = 'photo-235'), (select id from users where handle = 'priya'), 'This is stunning.', now() - interval '14017 minutes'),
            ((select id from posts where seedPhoto = 'photo-235'), (select id from users where handle = 'jonas'), 'Is that film or digital?', now() - interval '13109 minutes'),
            ((select id from posts where seedPhoto = 'photo-295'), (select id from users where handle = 'priya'), 'Is that film or digital?', now() - interval '15833 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'lena'), 'Wow. Just wow.', now() - interval '6305 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'priya'), 'Framed perfectly.', now() - interval '2973 minutes'),
            ((select id from posts where seedPhoto = 'photo-238'), (select id from users where handle = 'sam'), 'Is that film or digital?', now() - interval '11206 minutes'),
            ((select id from posts where seedPhoto = 'photo-14'), (select id from users where handle = 'priya'), 'This is stunning.', now() - interval '6624 minutes'),
            ((select id from posts where seedPhoto = 'photo-14'), (select id from users where handle = 'sam'), 'Need a print of this.', now() - interval '13527 minutes');

-- Everything older than a day has been seen.
update notifications set readAt = now() where createdAt < now() - interval '1 day';
